### ISSUE TITLE
In reader, in Firefox, videos are not launched

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/javascript#199]
See for example wind 555, page 24.

@serverfire can this be fixed?

**Comment by serverfire** [comment]
@libreliodev video.js does have a bug in it. But after installing new version of video.js. Bug has resolved.
But video is still not playing. And also firefox's video player is not playing the same video.
Probably it's not supported in Firefox.
I believe this issue is related to firefox itself.
Maybe we can fix it by using flash player by default.

**Comment by libreliodev** [comment]
@serverfire Ok, thanks. We'll possibly fix this later.

**Comment by libreliodev** [comment]
Successfully tested
